name: Release scriptor
on:
  push:
    paths: "scriptor/**/*"
    branches: main
jobs:
  check:
    name: Run checks
    uses: ./.github/workflows/check-scriptor.yaml
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: check
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          sparse-checkout: scriptor
      - name: Set up bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Move to scriptor directory
        run: cd scriptor
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun run semantic-release
